---
- name: Deploy OPA Plan Change Window Policy
  hosts: "{{ opa_server | default('all') }}"
  gather_facts: yes
  become: yes

  pre_tasks:  
  # Input time format: 2025-07-24 22:00:00
  - name: Convert AEST plan_change_start_hour to UTC hour
    set_fact:
      plan_change_start_hour: "{{ (plan_change_start_time[11:13]|int - 10 + 24) % 24 }}"
      plan_change_end_hour: "{{ (plan_change_end_time[11:13]|int - 10 + 24) % 24 }}"

  - name: Print plan change window configuration
    debug:
      msg: "Plan Change Window Configuration: Start Hour: {{ plan_change_start_hour }} End Hour: {{ plan_change_end_hour }}"

  roles:
    - role: ssa_demo.opa_server.plan_change_opa_policy
